-- Idempotent setup for Aurum's shared-database medallion topology.
-- AUTHORITATIVE ENTRY POINT: python -m src.db_config (src.db_config.apply_role_setup())
--
-- Note: All schema creation, role definitions, memberships, USAGE/SELECT grants,
-- and default privileges are authoritatively managed by python -m src.db_config.
-- Execute setup via: python -m src.db_config
