"""AST structural safety gate for Aurum generated SQL."""

from __future__ import annotations

import re

import sqlglot
from sqlglot import exp

from src.db_config import LayerSchemas, PipelineLayer, load_layer_schemas, resolve_layer_schema


class SqlSafetyViolation(Exception):
    """Raised when generated SQL fails structural AST safety checks."""
    pass


_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_CANDIDATE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*_candidate_[A-Za-z0-9_]+$")
_COMMENT_RE = re.compile(r"(--|/\*)")
_FORBIDDEN_KEYWORDS_RE = re.compile(
    r"\b(DROP|DELETE|UPDATE|TRUNCATE|ALTER|GRANT|REVOKE|COPY|INSERT|MERGE|CALL|DO|VACUUM|ANALYZE|INTO)\b",
    re.IGNORECASE,
)
_IF_NOT_EXISTS_RE = re.compile(r"\bIF\s+NOT\s+EXISTS\b", re.IGNORECASE)
_FORBIDDEN_NODES = (
    exp.Drop,
    exp.Alter,
    exp.Update,
    exp.Insert,
    exp.Delete,
    exp.TruncateTable,
    exp.Grant,
    exp.Command,
)


def _is_select_like(expression: exp.Expression) -> bool:
    return isinstance(expression, (exp.Select, exp.Union, exp.Intersect, exp.Except))


def _validate_candidate_name(table_name: str, run_id: str | None) -> None:
    if not _CANDIDATE_RE.match(table_name):
        raise SqlSafetyViolation(
            f"Generated tables must be named <target>_candidate_<run_id>, found: {table_name}"
        )
    if run_id is not None:
        if not _IDENTIFIER_RE.match(run_id):
            raise SqlSafetyViolation(f"Unsafe run id: {run_id}")
        suffix = f"_candidate_{run_id}"
        if not table_name.endswith(suffix):
            raise SqlSafetyViolation(
                f"Candidate table must end with {suffix}, found: {table_name}"
            )


def validate_generated_sql(
    sql_str: str,
    *,
    run_id: str | None = None,
    layer_schemas: LayerSchemas | None = None,
) -> str:
    """Validate a single SELECT or CREATE TABLE AS SELECT generated by the LLM."""
    if not sql_str or not sql_str.strip():
        raise SqlSafetyViolation("Empty SQL statement.")
    if _COMMENT_RE.search(sql_str):
        raise SqlSafetyViolation("SQL comments are not allowed in generated SQL.")
    if _FORBIDDEN_KEYWORDS_RE.search(sql_str):
        raise SqlSafetyViolation("Forbidden SQL keyword found.")
    if _IF_NOT_EXISTS_RE.search(sql_str):
        raise SqlSafetyViolation("CREATE TABLE IF NOT EXISTS is not allowed for candidates.")

    try:
        statements = sqlglot.parse(sql_str, read="postgres")
    except Exception as e:
        raise SqlSafetyViolation(f"SQL parsing failed: {e}")

    if not statements:
        raise SqlSafetyViolation("Empty SQL statement.")

    valid_stmts = [s for s in statements if s is not None]

    if len(valid_stmts) != 1:
        raise SqlSafetyViolation(f"Only exactly one SQL statement is allowed, found {len(valid_stmts)}.")

    stmt = valid_stmts[0]

    if not isinstance(stmt, exp.Create) and not _is_select_like(stmt):
        raise SqlSafetyViolation(f"Statement must be SELECT or CREATE TABLE AS, found: {type(stmt).__name__}")

    for node_type in _FORBIDDEN_NODES:
        for node in stmt.find_all(node_type):
            raise SqlSafetyViolation(f"Forbidden operation found: {type(node).__name__}")

    if isinstance(stmt, exp.Create):
        if stmt.args.get("kind") != "TABLE":
            raise SqlSafetyViolation(f"Only CREATE TABLE is allowed in DDL, found {stmt.args.get('kind')}.")

        expression = stmt.args.get("expression")
        if not expression or not _is_select_like(expression):
            raise SqlSafetyViolation("CREATE TABLE must have an AS SELECT body.")

        this = stmt.args.get("this")
        if not this:
            raise SqlSafetyViolation("Missing table name in CREATE TABLE.")

        table_name = this.name
        _validate_candidate_name(table_name, run_id)

        schema_node = this.args.get("db")
        if not schema_node:
            raise SqlSafetyViolation("CREATE TABLE must specify a target schema.")

        schemas = layer_schemas or load_layer_schemas()
        schema_name = schema_node.name
        allowed_schemas = {
            resolve_layer_schema(PipelineLayer.SILVER, schemas),
            resolve_layer_schema(PipelineLayer.GOLD, schemas),
        }
        if schema_name not in allowed_schemas:
            raise SqlSafetyViolation(
                f"Target schema must be one of {sorted(allowed_schemas)}, found: {schema_name}"
            )

    return stmt.sql(dialect="postgres")
