"""AST structural safety gate for Aurum generated SQL."""

from __future__ import annotations

import re

import sqlglot
from sqlglot import exp

from src.db_config import LayerSchemas, load_layer_schemas


class SqlSafetyViolation(Exception):
    """Raised when generated SQL fails structural AST safety checks."""
    pass


_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_CANDIDATE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*_candidate_[A-Za-z0-9_]+$")
_COMMENT_RE = re.compile(r"(--|/\*)")

_IF_NOT_EXISTS_RE = re.compile(r"\bIF\s+NOT\s+EXISTS\b", re.IGNORECASE)
_FORBIDDEN_NODES = (
    exp.Drop,
    exp.Alter,
    exp.Update,
    exp.Insert,
    exp.Delete,
    exp.TruncateTable,
    exp.Grant,
    exp.Command,
)


def _is_select_like(expression: exp.Expression) -> bool:
    return isinstance(expression, (exp.Select, exp.Union, exp.Intersect, exp.Except))


def _validate_candidate_name(table_name: str, run_id: str | None) -> None:
    if not _CANDIDATE_RE.match(table_name):
        raise SqlSafetyViolation(
            f"Generated tables must be named <target>_candidate_<run_id>, found: {table_name}"
        )
    if run_id is not None:
        if not _IDENTIFIER_RE.match(run_id):
            raise SqlSafetyViolation(f"Unsafe run id: {run_id}")
        suffix = f"_candidate_{run_id}"
        if not table_name.endswith(suffix):
            raise SqlSafetyViolation(
                f"Candidate table must end with {suffix}, found: {table_name}"
            )


def validate_generated_sql(
    sql_str: str,
    *,
    run_id: str | None = None,
    layer_schemas: LayerSchemas | None = None,
    expected_step_count: int | None = None,
) -> str:
    """Validate a single SELECT or CREATE TABLE AS SELECT generated by the LLM."""
    if not sql_str or not sql_str.strip():
        raise SqlSafetyViolation("Empty SQL statement.")
    if _COMMENT_RE.search(sql_str):
        raise SqlSafetyViolation("SQL comments are not allowed in generated SQL.")
    if _IF_NOT_EXISTS_RE.search(sql_str):
        raise SqlSafetyViolation("CREATE TABLE IF NOT EXISTS is not allowed for candidates.")

    try:
        statements = sqlglot.parse(sql_str, read="postgres")
    except Exception as e:
        raise SqlSafetyViolation(f"SQL parsing failed: {e}")

    if not statements:
        raise SqlSafetyViolation("Empty SQL statement.")

    valid_stmts = [s for s in statements if s is not None]

    if len(valid_stmts) != 1:
        raise SqlSafetyViolation(f"Only exactly one SQL statement is allowed, found {len(valid_stmts)}.")

    stmt = valid_stmts[0]

    if not isinstance(stmt, exp.Create) and not _is_select_like(stmt):
        raise SqlSafetyViolation(f"Statement must be SELECT or CREATE TABLE AS, found: {type(stmt).__name__}")
        
    if _is_select_like(stmt) and stmt.args.get("into"):
        raise SqlSafetyViolation("SELECT INTO is not allowed. Use CREATE TABLE AS SELECT.")

    for node_type in _FORBIDDEN_NODES:
        for node in stmt.find_all(node_type):
            raise SqlSafetyViolation(f"Forbidden operation found: {type(node).__name__}")

    if isinstance(stmt, exp.Create):
        if stmt.args.get("kind") != "TABLE":
            raise SqlSafetyViolation(f"Only CREATE TABLE is allowed in DDL, found {stmt.args.get('kind')}.")

        expression = stmt.args.get("expression")
        if not expression or not _is_select_like(expression):
            raise SqlSafetyViolation("CREATE TABLE must have an AS SELECT body.")

        this = stmt.args.get("this")
        if not this:
            raise SqlSafetyViolation("Missing table name in CREATE TABLE.")

        table_name = this.name
        _validate_candidate_name(table_name, run_id)

        schema_node = this.args.get("db")
        if not schema_node:
            raise SqlSafetyViolation("CREATE TABLE must specify a target schema.")

        schemas = layer_schemas or load_layer_schemas()
        schema_name = schema_node.name
        allowed_schemas = {
            schemas.silver_candidates,
            schemas.gold_candidates,
        }
        if schema_name not in allowed_schemas:
            raise SqlSafetyViolation(
                f"Target schema must be one of {sorted(allowed_schemas)}, found: {schema_name}"
            )

    if expected_step_count is not None:
        if isinstance(stmt, exp.Create):
            select_expr = stmt.args.get("expression")
            with_clause = select_expr.args.get("with") if select_expr else None
        else:
            with_clause = stmt.args.get("with")

        ctes = with_clause.expressions if with_clause else []
        if len(ctes) != expected_step_count:
            raise SqlSafetyViolation(f"Expected exactly {expected_step_count} CTEs, found {len(ctes)}.")

    return stmt.sql(dialect="postgres")

def execute_candidate_sql(sql_str: str, conn, run_id: str | None = None) -> None:
    """Execute LLM-generated SQL and immediately transfer ownership of the created candidate table."""
    import psycopg.sql as psql
    
    # 1. Validate the SQL (will raise SqlSafetyViolation if malicious/invalid)
    validated_sql = validate_generated_sql(sql_str, run_id=run_id)
    
    # 2. Extract target table and schema for the ALTER statement
    stmt = sqlglot.parse_one(validated_sql, read="postgres")
    
    if isinstance(stmt, exp.Create):
        this = stmt.args.get("this")
        target_schema = this.args.get("db").name
        target_table = this.name
    else:
        # If it's just a SELECT (which is allowed by validate_generated_sql for preview),
        # we don't have a table to hand off.
        with conn.cursor() as cur:
            cur.execute(validated_sql)
        return

    with conn.cursor() as cur:
        # Execute the validated LLM statement to create the table
        cur.execute(validated_sql)
        # Immediately transfer ownership to aurum_promotion
        cur.execute(psql.SQL("ALTER TABLE {}.{} OWNER TO aurum_promotion").format(
            psql.Identifier(target_schema), psql.Identifier(target_table)
        ))
